version: '3'
services:
  postgres:
    image: postgres:15.2
    ports:
      - '5432:5432'
    networks:
      - pern-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
networks:
  pern-app:
    driver: bridge
volumes:
  postgres-data:
    driver: local
