name: Keto Train CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose-db.yml up -d
        docker-compose -f docker-compose-keto-api.yml up -d

    - name: Build iOS
      if: runner.os == 'macOS'
      run: |
        cd client/ios
        pod install
        xcodebuild -workspace KetoLimit.xcworkspace -scheme KetoLimitRelease -sdk iphonesimulator -configuration Release build

    - name: Build Android
      run: cd client/android && ./gradlew assembleRelease

    - name: Build Docker Images
      run: |
        docker build -t keto-api-server ./server/
        docker build -t  postgres:15.3 ./postgres

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 861915720830.dkr.ecr.$AWS_REGION.amazonaws.com
        docker tag keto-api-server:latest 861915720830.dkr.ecr.$AWS_REGION.amazonaws.com/keto-api-server:latest
        docker push 861915720830.dkr.ecr.$AWS_REGION.amazonaws.com/keto-api-server:latest
        docker tag postgres:15.3:latest 861915720830.dkr.ecr.$AWS_REGION.amazonaws.com/postgres:15.3:latest
        docker push 861915720830.dkr.ecr.$AWS_REGION.amazonaws.com/postgres:15.3:latest
        docker tag redis/redis-stack:latest 861915720830.dkr.ecr.$AWS_REGION.amazonaws.com/redis:latest
        docker push 861915720830.dkr.ecr.$AWS_REGION.amazonaws.com/redis:latest